#### [Article on NN from Scratch](https://www.analyticsvidhya.com/blog/2020/07/neural-networks-from-scratch-in-python-and-r/)

In [2]:
# importing the library
import numpy as np

# creating the input array
# batch size - 3; number of features - 4
X=np.array([[1,0,1,0],
            [1,0,1,1],
            [0,1,0,1]])

print ('\n Input:')
print(X)


 Input:
[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]


In [3]:
# creating the output array
# output corresponding to each input sample

y=np.array([[1],
            [1],
            [0]])

print ('\n Actual Output:')
print(y)


 Actual Output:
[[1]
 [1]
 [0]]


In [4]:
# defining the Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

#### [Calculating derivative of sigmoid function](https://towardsdatascience.com/derivative-of-the-sigmoid-function-536880cf918e)

In [5]:
# derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)

In [6]:
# initializing the variables
epoch=5000 # number of training iterations
lr = 0.1 # learning rate
inputlayer_neurons = X.shape[1] # number of features in data set
hiddenlayer_neurons = 3 # number of hidden layers neurons
output_neurons = 1 # number of neurons at output layer

In [7]:
# initializing weight and bias
weight_h = np.random.uniform(size = (hiddenlayer_neurons, inputlayer_neurons)) # (number of neurons in hidden layer,  number of neurons in input layer)
bias_h = np.random.uniform(size = (1,hiddenlayer_neurons)) # (1, number of neurons in hidden layer)
weight_out = np.random.uniform(size = (output_neurons, hiddenlayer_neurons)) # (1, number of neurons in hidden layer)
bias_out = np.random.uniform(size = (1,output_neurons)) 

#### [Back Propagation Calculation](https://mattmazur.com/2015/03/17/a-step-by-step-backpropagation-example/)
#### [Back propagation whole code](https://github.com/mattm/simple-neural-network)

In [9]:
# training the model
for i in range(epoch):

    ### Forward Propogation
    hidden_layer_input = np.dot(X, weight_h.T) + bias_h # output_shape --> (number of training samples, number of hidden neurons); bias value will be added to row
    hiddenlayer_activations = sigmoid(hidden_layer_input) # sigmoid of each value in input matrix
    
    output_layer_input = np.dot(hiddenlayer_activations, weight_out.T) + bias_out # output_shape --> (number of training samples, 1)

    output_activations = sigmoid(output_layer_input) # shape - (number of input samples, 1)



    ### Backpropagation
    Error = y - output_activations # derivative of error wrt output; shape -- (number of input samples, 1)

    slope_output_layer = derivatives_sigmoid(output_activations) # derivative on final output; shape - (number of input samples, 1)
    delta_output = Error * slope_output_layer # calculating delta output; "row wise multiplication"; shape --(number of input samples, 1)

    slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations) # derivative of output from hidden layer; shape -- (number of training samples, number of hidden neurons)  
    Error_at_hidden_layer = delta_output.dot(weight_out) # shape -- (number of training samples, number of neurons in hidden layer) 
    
    delta_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer # element wise multiplication; shape -- # shape -- (number of training samples, number of neurons in hidden layer)
    
    # weight & bias updation
    weight_out += delta_output.T.dot(hiddenlayer_activations.T) * lr # shape -- (1, number of neurons in hidden layer)
    bias_out += np.sum(delta_output, axis=0, keepdims=True) * lr # shape -- (1, 1)
    weight_h += delta_hiddenlayer.T.dot(X) *  lr # (number of neurons in hidden layer,  number of neurons in input layer) 
    bias_h += np.sum(delta_hiddenlayer, axis=0,keepdims=True) *lr # (1, number of neurons in hidden layer)

print ('\n Output from the model:')
print (output_activations)


 Output from the model:
[[0.97827167]
 [0.97459246]
 [0.03085085]]
