In [10]:
import numpy as np

# [Input layer with 4 Neurons] --> [Output layer with 3 neurons]




### Batch Input: Multiple input examples are supplied to NN


##### Batch size = 3; i.e., 3 input samples
##### Input layer --> 4 neurons; each input sample is of shape (4,) vector
##### Output layer --> 3 neurons; thus 3 weight vectors with shape (4,)
##### Biases --> 3 biases associated with each output neuron

In [9]:


inputs = [[1,2,3,2.5],
[2.0, 5.0, 1.0, 4.0],
[-1.5, 2.7, 3.3, 0.8]]

input_matrix = np.array(inputs) # shape - (3,4); 3 input samples, each having 4 features

weights = [[0.2, 0.8, 0.5, 1.0],
	[0.5, 0.91, 0.26, 0.5],
	[0.26, -0.27, 0.17, 0.87]]

wt_matrix = np.array(weights) # shape - (3,4); 3 sets of weights each associted with 1 output neuron, 4 weights each associated with 1 input neuron

biases = [2, 3, -0.5] # (3,)

# we need to take the weights.Transpose in order to multiply weights associated with each input sample
# wt_matrix.T matrix would be of size 4X3; 
# 3 biases will get added to each row of dot product's output (shape - (3,3))
output = np.dot(input_matrix, wt_matrix.T) + biases

print (output)
# each row represents output associated with 1 sample

[[ 7.8    7.35   1.905]
 [10.9   10.81   2.32 ]
 [ 6.31   5.965 -0.362]]


# [Input layer with 4 Neurons] --> [Hidden layer with 3 neurons] --> [Output layer with 3 Neurons]

In [11]:
# Input layer
# layer - 1
inputs = [[1,2,3,2.5],
[2.0, 5.0, 1.0, 4.0],
[-1.5, 2.7, 3.3, 0.8]]

input_matrix = np.array(inputs) # shape - (3,4); 3 input samples, each having 4 features

weights1 = [[0.2, 0.8, 0.5, 1.0],
	[0.5, 0.91, 0.26, 0.5],
	[0.26, -0.27, 0.17, 0.87]]

wt_matrix1 = np.array(weights) # shape - (3,4); 3 sets of weights each associted with 1 output neuron, 4 weights each associated with 1 input neuron

biases1 = [2, 3, -0.5] # (3,)

layer1_output = np.dot(input_matrix, wt_matrix1.T) + biases1



## layer - 2
layer2_input = layer1_output # 3X3

weights2 = [[0.2, 0.8, 0.5],
	[0.5, 0.91, 0.26],
	[0.26, -0.27, 0.17]]

wt_matrix2 = np.array(weights2) # 3X3

biases2 = [2, 3, -0.5] # (3,)

layer2_output = np.dot(layer2_input, wt_matrix2.T) + biases2
print(layer2_output)

[[10.3925  14.0838  -0.13265]
 [13.988   18.8903  -0.1903 ]
 [ 7.853   11.48903 -0.53149]]


### OOP to convert layers into individual objects

#### N.B: Weights are generally set in the range of [-1,1]
* starting point for weights could be [-0.1, 0.1]
* ##### Weights above 1, or higher weights may give rise to **Exploding Gradient** problem; wherein weights never converges
* ##### Very small weights, give rise to **Vanishing Gradient** problem; wherein weights become so small for initial layers that there is hardly any learnings

#### N.B: Feature Scaling (on input data) is required for NN. This is because gradient descent converge much faster with feature scaling than without it.

# [Input layer with 4 Neurons] --> [Hidden layer with 5 neurons] --> [Output layer with 2 Neurons]
* #### batch size = 3




In [14]:
np.random.seed(0)

# 3 input samples
# shape - (number of training ex, number of features/neuron)
X = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]

# class to add layers to our NN
class Layer_Dense:
    def __init__(self, cur_neurons, next_neurons):
      # cur_neurons - Number of neurons in current layer
      # next_neurons - Number of neurons in next layer
      # np.random.randn - Normally distributed data points in a matrix of shape(cur_neurons, next_neurons)
      # biases - array of zeros of shape (1,next_neurons)
      self.weights = 0.10 * np.random.randn(next_neurons, cur_neurons)
      self.biases = np.zeros((1, next_neurons))
      self.output = None

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights.T) + self.biases

layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X) # input matrix will be the input to first layer

#print(layer1.output)
layer2.forward(layer1.output) # output of first layer will be the input to next layer

print(layer2.output)

[[-0.35380693 -0.18662673]
 [-0.77493552 -0.36525802]
 [-1.19606411 -0.5438893 ]]
